name: portfolio
description: Youssef Lasheen's portfolio.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.2.2+4

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^3.1.4
  auto_size_text: ^3.0.0
  url_launcher: ^6.0.17
  auto_route: ^3.2.0

  implicitly_animated_reorderable_list: ^0.4.2
  firebase_core: ^1.10.6
  rive: ^0.8.1
  font_awesome_flutter: ^10.1.0
  mouse_parallax: ^1.1.0
  carousel_slider: ^4.0.0
  shimmer: ^2.0.0
  flutter_riverpod: ^1.0.3
  dismissible_page: ^0.7.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  auto_route_generator: ^3.1.0
  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: ^2.2.3+1


flutter_icons:
  android: "launcher_icon"
  image_path: "assets/icons/icon.png"

flutter_native_splash:
  color: "#212121"
  android: false
  ios: false
  image: assets/images/LLLogoClipArtOulinedWithSpacing.png
  web_image_mode: center
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/textures/
    - assets/animations/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: CustomIcons
      fonts:
        - asset: fonts/CustomIcons.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
