// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXG5hfEfLnSlS4xB02Hc4sq4QoJLdtF3k',
    appId: '1:23616548175:web:8645a9195f6294f50be93a',
    messagingSenderId: '23616548175',
    projectId: 'yousseflasheen-portfolio',
    authDomain: 'yousseflasheen-portfolio.firebaseapp.com',
    databaseURL: 'https://yousseflasheen-portfolio.firebaseio.com',
    storageBucket: 'yousseflasheen-portfolio.appspot.com',
    measurementId: 'G-QZM1EDTRDD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBvnvYkW6X4qxXWxR3fDtDdzyPlkftnj8',
    appId: '1:23616548175:android:895653cd5ab3007b0be93a',
    messagingSenderId: '23616548175',
    projectId: 'yousseflasheen-portfolio',
    databaseURL: 'https://yousseflasheen-portfolio.firebaseio.com',
    storageBucket: 'yousseflasheen-portfolio.appspot.com',
  );
}
